Implementation of first and last reduction
holoviz/datashader pull request #1093
Opened 2022-06-12 08:03 UTC by tselea

For my current work, it is useful for me to make use of the first([column]) and last([column]) reductions, which at the moment are implemented only for rasters.

For both reductions, I've initialised a numpy array with numpy.nan values ( create() method). The append() method is implemented as follows:

- first([column]): check if field is not null and if agg[y,x] is null (has not yet been filled), then set agg[y,x] = field
- last([column]): check if field is not null, then set agg[y,x] = field

For both reductions, the finalizez() method wraps the numpy array to a xarray DataArray (similar to the count() reduction)

Please let me know if you think this may be a good fit for the project.

2022-06-12 15:53 UTC, jbednar commented
That's super helpful, thanks! I approve adding these to Datashader and at a quick glance the code looks good, but I only had a minute to look at it. @ianthomas23 , can you look a little closer just in case?

2022-06-12 17:06 UTC, tselea commented
Thank you @jbednar for the reply! Glad to contribute. Please let me know if further changes are needed.

2022-06-13 12:24 UTC, ianthomas23 commented on datashader/reductions.py
>          raise NotImplementedError("first is currently implemented only for rasters")
This `NotImplementedError` needs a different explanation now, perhaps "first is not implemented for dask DataFrames"?

2022-06-13 12:33 UTC, ianthomas23 requested changes
This is looking good so far, I've left a few review comments.

The `NotImplementedError` needs the mention of dask because the `_combine` function is called for dask `DataFrames` to combine the results of the multiple dask partitions. We don't need to support this method of working because we will be unable to decide which was the overall `first`/`last`, so we just need to explicitly state that use of dask is not supported here.

We also need a test here, which will remove the Code Coverage complaints. I'd probably opt for a new test in `datashader/tests/test_pandas.py` using a small (5x5?) canvas and a single line with `x`, `y` and `z` values that crosses itself. Then use `canvas.lines(..., agg=ds.first("z"), ...)` and check the return against a known result, then do the same for `ds.last("z")`. If this isn't enough information I can help more!

2022-06-13 12:33 UTC, ianthomas23 commented on datashader/reductions.py
> -        raise NotImplementedError("last is currently implemented only for rasters")
As above.

2022-06-15 07:39 UTC, tselea commented
Thank you @ianthomas23 for the review! Sorry for the late response.

Your review comments and suggestions for test implementation were really helpful! Thanks! Hope I understood corectly. 
The line exemple that crosses itself that I used for testing is depicted below.
<img width="625" alt="line_example" src="https://user-images.githubusercontent.com/14962659/173770091-33300e73-b931-4ba0-a3a1-c932b8c0fe99.png">

Please let me know if further changes are needed.

2022-06-17 21:07 UTC, ianthomas23 requested changes
This is very nearly there. The tests are very clear, but you could make them simpler by only comparing the numpy arrays `agg.data` and `sol` rather than the xarray DataArrays. Then the `axis` and `lincoords` aren't needed at the top of the functions. If you can change this in both test functions and the extra couple of whitespace characters that I just found, it will be ready to merge.

2022-06-17 21:07 UTC, ianthomas23 commented on datashader/reductions.py
> +    def _append(x, y, agg,field):
```suggestion
    def _append(x, y, agg, field):
```

2022-06-17 21:07 UTC, ianthomas23 commented on datashader/reductions.py
> +    def _append(x, y, agg,field):
```suggestion
    def _append(x, y, agg, field):
```

2022-06-17 21:07 UTC, ianthomas23 commented on datashader/tests/test_pandas.py
> +    assert_eq_xr(agg, out)
```suggestion
    assert_eq_ndarray(agg, sol)
```

2022-06-18 08:49 UTC, tselea commented
I’ve updated the code based on your last review. Please let me know if further changes should be implemented.

I’m grateful for you taking the time to review the code and for all your suggestions. Thanks, @ianthomas23!

2022-06-18 13:45 UTC, ianthomas23 approved these changes
Thanks @tselea for your first PR. We hope to see you again soon!

2022-06-18 13:46 UTC, merged