1141 | Validate canvas width, height
holoviz/datashader pull request #1183
Opened 2023-02-15 11:32 UTC by Jap8nted

See issue https://github.com/holoviz/datashader/issues/1141.

When a canvas is created with plot_width=0 or plot_height=0 and the data is coming from dask, there is a core dump error, up to now, the error could just be reproduced on a machines running amd and intel. On Arm the problem does not appear. 

`from datashader import Canvas
from datashader.reductions import mean, sum, max, min
from dask import dataframe as ddf
def main():
    df = pd.DataFrame({"LON": [0, 1, 2, 3, 4], "LAT": [0, 1, 2, 3, 4], "VALUE": [0, 1, 2, 3, 4]})
    data = ddf.from_pandas(df, npartitions=1)
    cvs = Canvas(
        plot_width=0,
        plot_height=0
    )
    cvs.points(data, "LON", "LAT", agg=max("VALUE"))
if __name__ == "__main__":
    main()
`

2023-02-15 20:17 UTC, jbednar commented
Thanks. I'll leave it to @ianthomas23 to think about whether it's appropriate to raise an error or to return an empty array in this case; not sure which is e.g. less problematic for HoloViews.

2023-02-16 14:19 UTC, ianthomas23 commented
OK, so the options here are

1. Raise an error.
2. Continue as normal and return zero-sized DataArrays.

I'd be happy with either but my preference is for 1 as I'd rather detect the situation as soon as possible and report it immediately.

@Jap8nted Are you happy to continue with this PR?

If so, this fix is good, it is failing CI because the raised `ValueError` doesn't need to use an f-string. Also, it should have a test to confirm that the fix is good. A new test in `test_pandas.py` should suffice, perhaps just below `test_line_coordinate_lengths` and it can use similar `pytest.raises` logic to that test.

2023-02-17 08:26 UTC, Jap8nted commented
Hi, 

I will continue with it, @ianthomas23, a ok, got it, will fix the f-string as well.

2023-02-20 17:46 UTC, ianthomas23 requested changes
@Jap8nted This is functionally fine. I've manually tested it using `cudf` and `cudf-dask` as our CI doesn't do this for us and they both fail correctly.

I would rather call it `validate_size` than `validate_extend` so I have made a few suggested changes along those lines, and also a few changes to whitespace. If you could make those amendments it should be good to merge.

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/core.py
> +    def validate_extend(self, width, height):
```suggestion
    def validate_size(self, width, height):
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/core.py
> +            raise ValueError("Invalid extend plot_width and plot_height must be bigger than 0")
```suggestion
            raise ValueError("Invalid size: plot_width and plot_height must be bigger than 0")
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_dask.py
> +
```suggestion


```
I'd like to keep the whitespace consistent.

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_dask.py
> +def test_canvas_extend():
```suggestion
def test_canvas_size():
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_dask.py
> +
```suggestion
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_dask.py
> +    msg = r'Invalid extend plot_width and plot_height must be bigger than 0'
```suggestion
    msg = r'Invalid size: plot_width and plot_height must be bigger than 0'
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_pandas.py
> +
```suggestion
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_pandas.py
> +def test_canvas_extend():
```suggestion
def test_canvas_size():
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_pandas.py
> +
```suggestion
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/tests/test_pandas.py
> +    msg = r'Invalid extend plot_width and plot_height must be bigger than 0'
```suggestion
    msg = r'Invalid size: plot_width and plot_height must be bigger than 0'
```

2023-02-20 17:46 UTC, ianthomas23 commented on datashader/core.py
> +        if width == 0 or height == 0:
```suggestion
        if width <= 0 or height <= 0:
```
Just in case someone passes in a negative number.

2023-02-21 16:47 UTC, merged

2023-02-21 17:58 UTC, Jap8nted commented
Thanks for the comments and help @ianthomas23 and happy to help!